import type { Metadata } from "next";
import { Toaster } from 'react-hot-toast';
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <Header />
        <div className="w-11/12 mx-auto pt-20">
          {children}
        </div>
        <Footer />
      <Toaster />
      </body>
    </html>
  );
}
